### PR TITLE
PEP-0

### PR DESCRIPTION
**Pull request by mikealfare**
Establish rules around roles and responsibilities within PyRVA as well as identify members of each role.

### CODE REVIEW

**Review by briancohan — APPROVED** [review]

**Comment by Chris-May** [comment]
Thank you for all this work! I'm so grateful to have you two around to help create these artifacts!
I'd like to know the why behind the time frames connected to the promotion of members/organizers.

**Comment by briancohan** [comment]
> I'd like to know the why behind the time frames connected to the promotion of members/organizers.

There are three goals in developing structure to the organizer pool.

- Establish PyRVA as a Python Software Foundation (PSF) Fiscal Sponsoree to allow PyRVA to raise funds and accept donations.
- To moderate access control of PyRVA's digital assets (Meetup, Discord, Github, etc.).
- Create an organizer level that acknowledges individuals who are helping move PyRVA forward without the weight of responsibility for the organization.

The promotion/demotion mechanisms are designed to address the second item. Anyone can join the organizer team, but this codifies that we're not just going to give them full moderation privileges. Likewise, if someone with moderation privileges stops attending, this allows us to restrict their privileges until they are ready to return. In addition to moderation privileges, if someone were to reach out to PyRVA, this structure allows them to know who specifically to talk to. 

As for the attendance requirements, organizers should be active in the group. We recognize that life happens and think it's unreasonable to require 100% attendance, but they should have a sense of what the group is up to. In order to be promoted to Organizer or Co-Organizer, we felt that you have to demonstrate that you meet the requirements of your current level. We discussed setting the attendance requirements based on a 3-month or 6-month cycle and felt that 6-month cycles would provide more flexibility for organizers.

**Comment by Chris-May** [comment]
Thanks for the explanation, Brian. I should have been a little clearer. :)

I think this all sounds great. My only hesitation was with this line:

> Elevation to Organizer or Co-Organizer requires being in the Assistant Organizer role for at least six months.

I don't think it's bad, but I have a small concern that this could hamstring us in the future if we wanted to promote someone in less than six months. I'm sure we had great reasons for this, I just can't remember what they were.

**Comment by briancohan** [comment]
We felt like all the timelines should be the same for promotion and demotion. Mike brought up the following point: 

> In order to be promoted to Organizer or Co-Organizer, we felt that you have to demonstrate that you meet the requirements of your current level.

If you recall, we had a brief moment where all three of us got hit hard by life and had to take things easy for a bit. Mike and I decided that (for the first draft) the 3-month cycle would be too short for the attendance requirements. We are certainly willing to discuss a cycle other than 6-months. 

In practice this really only affects moderation privileges and PSF contact information. If a situation arises where we feel we need to expedite something, we can always edit the guidelines during an organizer meeting. But as it stands, Assistant Organizers will have access to the resources needed to run a meeting and edit events on Meetup.

**Comment by Chris-May** [comment]
Thanks! Sounds great!

**Pull request merged**
